version: "3.1"
services:
  wwwclient:
    build:
      context: ./client
    image: wwwclient
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - wwwserver
    ports:
      - "3000:3000"
  wwwserver:
    build:
      context: ./server
    image: wwwserver
    ports:
      - "3001:3001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
